# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import sports_pb2 as sports__pb2


class SportsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSports = channel.unary_unary(
                '/SportsService/GetSports',
                request_serializer=sports__pb2.EmptyRequest.SerializeToString,
                response_deserializer=sports__pb2.GetSportsResponse.FromString,
                )


class SportsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSports(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SportsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSports': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSports,
                    request_deserializer=sports__pb2.EmptyRequest.FromString,
                    response_serializer=sports__pb2.GetSportsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SportsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SportsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSports(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SportsService/GetSports',
            sports__pb2.EmptyRequest.SerializeToString,
            sports__pb2.GetSportsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
